#
# This docker image is for launching test purpose trino cluster.
#

FROM arm64v8/openjdk:11
MAINTAINER lewuathe

ARG VERSION=355
ARG BASE_URL=https://repo1.maven.org/maven2
ENV TRINO_VERSION=${VERSION}
ENV TRINO_HOME=/usr/local/trino
ENV BASE_URL=${BASE_URL}

# install dev tools
RUN apt-get update && apt-get install -y curl tar sudo rsync python wget python-pip python-dev build-essential && pip install jinja2

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin

WORKDIR /usr/local
RUN \
    wget -q ${BASE_URL}/io/trino/trino-server/${TRINO_VERSION}/trino-server-${TRINO_VERSION}.tar.gz && \
    tar -xvzf trino-server-${TRINO_VERSION}.tar.gz -C /usr/local/ && \
    ln -s /usr/local/trino-server-${TRINO_VERSION} $TRINO_HOME && \
    rm -f trino-server-${TRINO_VERSION}.tar.gz

ADD scripts ${TRINO_HOME}/scripts

# Create data dir
RUN mkdir -p $TRINO_HOME/data
VOLUME ["$TRINO_HOME/data"]
