#
# This docker image is for launching test purpose trino cluster.
#

FROM arm64v8/openjdk:11

ARG VERSION
ENV TRINO_VERSION=${VERSION}
ENV TRINO_HOME=/usr/local/trino
ENV BASE_URL=https://repo1.maven.org/maven2

# install dev tools
RUN apt-get update
RUN apt-get install -y curl tar sudo rsync python wget python-pip python-dev build-essential
RUN pip install jinja2

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin

WORKDIR /usr/local
#ADD trino-server-${TRINO_VERSION}.tar.gz /usr/local
RUN wget -q ${BASE_URL}/io/trino/trino-server/${TRINO_VERSION}/trino-server-${TRINO_VERSION}.tar.gz
RUN tar xvzf trino-server-${TRINO_VERSION}.tar.gz -C /usr/local/
RUN ln -s /usr/local/trino-server-${TRINO_VERSION} $TRINO_HOME

ADD scripts ${TRINO_HOME}/scripts

# Create data dir
RUN mkdir -p $TRINO_HOME/data
VOLUME ["$TRINO_HOME/data"]
