#
# This docker image is for launching test purpose trino cluster.
#

FROM amazoncorretto:11

ARG VERSION
ENV trino_VERSION=${VERSION}
ENV trino_HOME=/usr/local/trino
ENV BASE_URL=https://repo1.maven.org/maven2

# install dev tools
RUN yum update -y
RUN yum install -y curl tar sudo rsync python wget python-pip python-dev build-essential
RUN pip install jinja2

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin

WORKDIR /usr/local
ADD trino-server-${trino_VERSION}.tar.gz /usr/local
#RUN tar xvzf trino-server-${trino_VERSION}.tar.gz -C /usr/local/
RUN ln -s /usr/local/trino-server-${trino_VERSION} $trino_HOME

ADD scripts ${trino_HOME}/scripts

# Create data dir
RUN mkdir -p $trino_HOME/data
VOLUME ["$trino_HOME/data"]
